"use client";
import { Drawer, Link } from "@mui/material";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { FaShoppingCart } from "react-icons/fa";
import { HiMenu } from "react-icons/hi";
import { HiUserCircle } from "react-icons/hi2";
import { MdFavorite } from "react-icons/md";
import Footer from "./components/footer";
import IconLink from "./components/icon-link";
import { SearchBar } from "./components/search-bar";
import "./globals.css";
import { Category } from "./models/category";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getCategories(): Promise<any> {
  const response = await fetch("api/categories");

  return response.json();
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isActive, setActive] = useState(false);
  const [categories, setCategories] = useState<Category[]>([]);

  const toggleActive = (_: any) => {
    setActive(!isActive);
  };

  useEffect(() => {
    const data = getCategories();
    data.then((data) => setCategories(data));
  });


  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="header">
          <button className="menuBtn" onClick={toggleActive}>
            {<HiMenu size={53} color="white"></HiMenu>}
          </button>
          <Drawer anchor="left" open={isActive} onClose={toggleActive}>
            <div className="text-[white] text-lg font-[500] flex flex-col px-6 py-6">
              {categories.map((item) => {
                return (
                  <Link href={"/"} key={item.id}>
                    {item.C_name}
                  </Link>
                );
              })}
            </div>
          </Drawer>

          <SearchBar />
          <div className="flex flex-row justify-around">
            <IconLink path={"/"} Icon={HiUserCircle} />
            <IconLink path={"/"} Icon={MdFavorite} />
            <IconLink path={"/"} Icon={FaShoppingCart} size={49} />
          </div>
        </div>
        {children}

        <Footer />
      </body>
    </html>
  );
}
